import Head from 'next/head'

import { Footer } from '@/components/Footer/Footer'
import { Home } from '@/views/Home'

export default function HomePage () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Home />

      <main>
        <Footer />
      </main>
    </>
  )
}
